<?php


namespace Classes;


class ActivityView extends ActivityContr
{

    public function createActivity(string $activityName, string $activityType, string $activityResourceId, string $activityOwnerId) :bool {

            $this->setCActivityId();
            $this->setCActivityName($activityName);
            $this->setCActivityOwner($activityOwnerId);
            $this->setCActivityResourceId($activityResourceId);
            $this->setCActivityType($activityType);
            return self::createActivityStatus();
    }

    public function createUserLoggedInActivity(string $activityOwnerId): bool
    {
        $this->setCActivityId();
        $this->setCActivityOwner($activityOwnerId);
        return parent::userLoggedInActivityStatus();
    }

    public function getOwnerActivity(string $activityOwnerId): bool|array
    {
            $this->setCActivityOwner($activityOwnerId);
        return parent::getOwnerActivityStatus(); // TODO: Change the autogenerated stub
    }

    public function getFriendsActivity(string $activityOwnerId): bool|array
    {
            $this->setCActivityOwner($activityOwnerId);
        return parent::getActivityOnFriendsStatus();
    }

    public function updateLogoutActivity(string $activityOwnerId): bool
    {
            $this->setCActivityOwner($activityOwnerId);
        return parent::updateLogoutActivityStatus();
    }

    public function updateLoginActivity(string $activityOwnerId): bool|array
    {
            $this->setCActivityOwner($activityOwnerId);
        return parent::updateLoginActivityStatus();
    }

    public function getUserNotificationActivity(string $activityOwnerId): array {
        $this->setCActivityOwner($activityOwnerId);
        return parent::getUserNotificationActivityStatus();
    }

    public function getActivityOnUserItemsClaimed(string $activityOwnerId): bool|array
    {
        $this->setCActivityOwner($activityOwnerId);
        return parent::getActivityOnUserItemsClaimedStatus();
    }

    protected function getActivityOnUserItemLikes(string $activityOwnerId): bool|array
    {
        $this->setCActivityOwner($activityOwnerId);
        return parent::getActivityOnUserItemLikesStatus();
    }


}

