<?php


namespace Classes;


class ApplicationContr extends Application
{
    protected function setCApplicationId(): void
    {
        $applicantId = Utilities::genUniqueId("app");
        parent::setApplicationId($applicantId);
    }
    protected function setCApplicantRole(string $applicantRole): void
    {
        parent::setApplicantRole($applicantRole);
    }

    protected function addCApplicationId($applicantId): void
    {
        $applicantId = Utilities::cleanData($applicantId);
        parent::setApplicationId($applicantId);
    }

  protected function setCApplicantId(string $applicantId): void
  {
      $applicantId = Utilities::cleanData($applicantId);
      parent::setApplicantId($applicantId); // TODO: Change the autogenerated stub
  }

}