<?php


namespace Classes;


class FinderContr extends Finder
{
    protected function setCFinderAccount(string $finderAccount): void
    {
        parent::setFinderAccount($finderAccount);
    }

    protected function setCFinderAddress(string $finderAddress): void
    {
        parent::setFinderAddress($finderAddress);
    }

    protected function setCFinderCredit(float $finderCredit): void
    {
        parent::setFinderCredit($finderCredit);
    }

    protected function setCFinderId(): void
    {
        $finderId = Utilities::genUniqueId("fin");
        parent::setFinderId($finderId);
    }

    protected function addCFinderId( string $id): void {
        parent::setFinderId($id);
    }

    protected function setCFinderName(string $finderFullName): void
    {
        parent::setFinderName($finderFullName);
    }

    protected function setCItemSubmittedId(string $itemSubmittedId): void
    {
        parent::setItemSubmittedId($itemSubmittedId);
    }

    protected function setCFinderNationalIdCard(string $finderNationalIdCard): void
    {
        parent::setFinderNationalIdCard($finderNationalIdCard);
    }

    protected function setCFinderPhone(string $finderPhone): void
    {
        parent::setFinderPhone($finderPhone);
    }

    protected function setCFinderEarnings(float $finderEarnings): void
    {
        parent::setFinderEarnings($finderEarnings); // TODO: Change the autogenerated stub
    }

}