<?php

namespace Classes;

class NotificationSettingsView extends NotificationSettingsContr
{

    public function getUserNotificationSettings(string $userId): ?array {
        $this->setUserId($userId);
        return $this->getUserNotificationSettingsResult();
    }

    public function enableNotificationSettings(
        string $userId
//        int $notificationEnabled,
//        int $notificationSound,
//        int $notificationFriendRequest,
//        int $notificationComment,
//        int $notificationMessage,
//        int $notificationFollower,
//        int $notificationCourse,
//        int $notificationPayment
    ): bool {
        $this->setCSettingId();
        $this->setCUserId($userId);
//        $this->setCNotificationEnabled($notificationEnabled);
//        $this->setCNotificationSound($notificationSound);
//        $this->setCNotificationFriendRequest($notificationFriendRequest);
//        $this->setCNotificationComment($notificationComment);
//        $this->setNotificationMessage($notificationMessage);
//        $this->setNotificationFollower($notificationFollower);
//        $this->setCNotificationCourse($notificationCourse);
//        $this->setCNotificationPayment($notificationPayment);

        return $this->enableInitNotificationStatus();
    }

    public function enabledCourseNotifications(string $userId,int $notificationCourse): bool
    {
        $this->setCUserId($userId);
        $this->setCNotificationCourse($notificationCourse);
        return parent::enabledCourseNotificationsStatus();
    }

    public function enabledFollowerNotifications(string $userId, int $notificationFollower ): bool
    {

        $this->setCUserId($userId);
        $this->setCNotificationFollower($notificationFollower);
        return parent::enabledFollowerNotificationsStatus();
    }

    public function enabledFriendRequestNotifications(string $userId, int $notificationFriendRequest,): bool
    {
        $this->setCUserId($userId);
        $this->setCNotificationFriendRequest($notificationFriendRequest);
        return parent::enabledFriendRequestNotificationsStatus();
    }

    public function enabledMessageNotifications(string $userId, int $notificationMessage): bool
    {
        $this->setCUserId($userId);
        $this->setCNotificationMessage($notificationMessage);
        return parent::enabledMessageNotificationsStatus();
    }

    public function reEnabledNotifications(string $userId,int $notificationEnabled,): bool
    {
        $this->setCUserId($userId);
        $this->setCNotificationEnabled($notificationEnabled);
        return parent::enabledNotificationsStatus();
    }


    public function enabledPaymentNotifications(string $userId ,int $notificationPayment): bool
    {
        $this->setCUserId($userId);
        $this->setCNotificationPayment($notificationPayment);
        return parent::enabledPaymentNotificationsStatus();
    }

    public function enabledSoundNotifications(string $userId, int $notificationSound): bool
    {
        $this->setCUserId($userId);
        $this->setCNotificationSound($notificationSound);
        return parent::enabledSoundNotificationsStatus();
    }


    public function enableNotificationComments(string $userId, int $notificationComment): bool
    {
        $this->setCUserId($userId);
        $this->setCNotificationComment($notificationComment);
        return parent::enableNotificationCommentsStatus(); // TODO: Change the autogenerated stub
    }


}