<?php


namespace Classes;


class RequestContr extends Request
{
    protected function setCRequestItemColor(string $requestItemColor): void
    {
        $requestItemColor = Utilities::cleanData($requestItemColor);
        parent::setRequestItemColor($requestItemColor);
    }

    protected function setCRequestItemDescription(string $requestItemDescription): void
    {
        $requestItemDescription = Utilities::cleanData($requestItemDescription);
        parent::setRequestItemDescription($requestItemDescription);
    }

    protected function addCRequestItemId(string $requestItemId): void
    {   $requestItemId = Utilities::cleanData($requestItemId);
        parent::setRequestItemId($requestItemId);
    }

    protected function setCRequestItemId(): void
    {
        $requestItemId = Utilities::genUniqueId("req");
        parent::setRequestItemId($requestItemId);
    }

    protected function setCRequestItemImage(string $requestItemImage): void
    {
        $requestItemImage = Utilities::cleanData($requestItemImage);
        parent::setRequestItemImage($requestItemImage);
    }

    protected function setCRequestItemName(string $requestItemName): void
    {
        $requestItemName = Utilities::cleanData($requestItemName);
        parent::setRequestItemName($requestItemName); // TODO: Change the autogenerated stub
    }

    protected function setCRequestItemSerial(string $requestItemSerial): void
    {
        $requestItemSerial = Utilities::cleanData($requestItemSerial);
        parent::setRequestItemSerial($requestItemSerial); // TODO: Change the autogenerated stub
    }

    protected function setCRequestItemValue(float $requestItemValue): void
    {
        $requestItemValue = Utilities::cleanData($requestItemValue);
        parent::setRequestItemValue($requestItemValue); // TODO: Change the autogenerated stub
    }

    protected function setCRequestItemSubmitter(string $requestItemSubmitter): void
    {
        parent::setRequestItemSubmitter($requestItemSubmitter); // TODO: Change the autogenerated stub
    }

}