<?php


namespace Classes;


class TotalContr extends Total
{

    protected function setCAdminFeeTotal(float $adminFeeTotal): void
    {
        $adminFeeTotal = Utilities::cleanData($adminFeeTotal);
        parent::setAdminFeeTotal($adminFeeTotal); // TODO: Change the autogenerated stub
    }

    protected function setCAgentFeeTotal(float $agentFeeTotal): void
    {
        $agentFeeTotal = Utilities::cleanData($agentFeeTotal);
        parent::setAgentFeeTotal($agentFeeTotal); // TODO: Change the autogenerated stub
    }

    protected function setCTotalValue(float $totalValue): void
    {
        parent::setTotalValue($totalValue); // TODO: Change the autogenerated stub
    }

    protected function setCHasAdditional(bool $hasAdditional): void
    {
        $hasAdditional = Utilities::cleanData($hasAdditional);
        parent::setHasAdditional($hasAdditional); // TODO: Change the autogenerated stub
    }

    protected function setCMainItemId(string $mainItemId): void
    {
        $mainItemId = Utilities::cleanData($mainItemId);
        parent::setMainItemId($mainItemId); // TODO: Change the autogenerated stub
    }


    protected function setCTotalReward(float $totalReward): void
    {
        $totalReward = Utilities::cleanData($totalReward);
        parent::setTotalReward($totalReward); // TODO: Change the autogenerated stub
    }

}